version: "3.8"
services:
  xmrig:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xmrig
    volumes:
      - /etc/localtime:/etc/localtime:ro
    #   environment:
    #     - REQUEST_TIMEOUT=320

    deploy:
      resources:
        limits:
          memory: 8096M
          cpus: '2.0'

